x-record-volumes: &record-volumes
  volumes:
    - ./pgfr_record:/pgfr_record:ro
    - ./pgfr_record/tests:/tests/record:ro

services:
  postgres15:
    <<: *record-volumes
  postgres16:
    <<: *record-volumes
  postgres17:
    <<: *record-volumes
  postgres18:
    <<: *record-volumes
