x-analyze-volumes: &analyze-volumes
  volumes:
    - ./pgfr_analyze:/pgfr_analyze:ro
    - ./pgfr_analyze/tests:/tests/analyze:ro

services:
  postgres15:
    <<: *analyze-volumes
  postgres16:
    <<: *analyze-volumes
  postgres17:
    <<: *analyze-volumes
  postgres18:
    <<: *analyze-volumes
